site_name: Release semantic commit
repo_url: https://github.com/raunifabricio/release-semantic-commit
theme:
  name: material
  language: pt-BR

nav:
  - Início: index.md
  - Sobre: sobre.md
  - Histórico de Commits: changelog.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
