site_name: Release Semantic Commit
site_description: Documentação oficial do meu projeto.
site_url: https://raunifabricio.github.io/release-semantic-commit/

theme:
  name: material
  language: pt
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
    - header.autohide
    - content.code.annotate
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/raunifabricio/release-semantic-commit
repo_name: GitHub

nav:
  - Home: changelog.md

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: false
      type: date
      locale: pt_BR
      timezone: America/Sao_Paulo

markdown_extensions:
  - markdown_include.include:
      base_path: .



