# .github/workflows/deploy_docs.yml
name: Deploy MkDocs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install commitizen mkdocs

      - name: Generate Changelog and Update Docs
        run: |
          cz changelog
          python scripts/update_index.py

      - name: Build and Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./site
