name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Gerar data de atualização
  run: |
    mkdir -p docs/includes
    echo "*Atualizado em: $(date '+%d/%m/%Y')*" > docs/includes/updated_date.md

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
